vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 4
vim.osofttabstop = 4
vim.o.shiftwidth = 4
vim.o.smartindent = true
vim.o.incsearch = true
vim.o.termguicolors = true
vim.o.swapfile = false
vim.g.material_style = "deep ocean"
